services:
  lexi-postgres:
    image: postgres:latest
    container_name: lexi-postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "Lexi"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  lexi:
    build:
      context: ./src/LexiService/
    container_name: lexi
    command: dotnet run --urls "https://0.0.0.0:8042;http://0.0.0.0:8043"
    ports:
      - "8042:8080"
      - "8043:8081"
    volumes:
      - ./src/LexiService:/app
    environment:
      DATABASE_HOST: "lexi-postgres"
      DATABASE_PORT: "5432"
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  postgres-data: